(ns kotoba.lang.pqh.pq
  "Post-quantum hybrid layer (suite \"pqh-v1\") -- JVM port of pqh's
   src/pq.ts. Per ADR-2606111300 (etzhayyim/root):

     KEM: X25519 + ML-KEM-768 (FIPS 203) -> HKDF-SHA256 combiner.
     SIG: ML-DSA-65 (FIPS 204) half of the Ed25519+ML-DSA-65 dual signature
          (the Ed25519 half lives in kotoba.lang.pqh.did-signal, via the
          kotoba-lang/ed25519 library).

   All three PQC/asymmetric primitives here (X25519, ML-KEM-768, ML-DSA-65)
   are Bouncy Castle (`bcprov-jdk18on` 1.79). Each was independently
   cross-verified byte-for-byte against this repo's own npm deps
   (@noble/curves, @noble/post-quantum, @noble/hashes) in this port's test
   suite (kotoba.lang.pqh.pq-test) using vectors generated by
   @noble/curves/ed25519 (x25519), @noble/post-quantum/ml-kem.js, and
   @noble/post-quantum/ml-dsa.js -- see the README \"Clojure/CLJC port\"
   section for exactly what was verified and one documented gap (below).

   JVM-only: ML-KEM-768/ML-DSA-65 have no Web Crypto browser primitive at
   all, so this whole namespace is JVM-only by necessity (not a scope
   choice)."
  (:require [kotoba.lang.pqh.util :as u])
  (:import (org.bouncycastle.crypto.params X25519PrivateKeyParameters X25519PublicKeyParameters
                                            HKDFParameters)
           (org.bouncycastle.crypto.generators HKDFBytesGenerator)
           (org.bouncycastle.crypto.digests SHA256Digest)
           (org.bouncycastle.pqc.crypto.mlkem MLKEMParameters MLKEMKeyPairGenerator
                                               MLKEMKeyGenerationParameters
                                               MLKEMPublicKeyParameters MLKEMPrivateKeyParameters
                                               MLKEMGenerator MLKEMExtractor)
           (org.bouncycastle.pqc.crypto.mldsa MLDSAParameters MLDSAPrivateKeyParameters
                                               MLDSAPublicKeyParameters MLDSASigner)
           (java.security SecureRandom)))

(def PQ-SUITE "pqh-v1")

(def X25519-PUBLIC-BYTES 32)
(def MLKEM768-PUBLIC-BYTES 1184)
(def MLKEM768-CIPHERTEXT-BYTES 1088)
(def MLDSA65-PUBLIC-BYTES 1952)
(def HYBRID-SHARED-SECRET-BYTES 32)

(def ^:private KEM-COMBINER-SALT (.getBytes "etzhayyim/pqh-v1/kem" "UTF-8"))
(def ^:private secure-random (SecureRandom.))
(def ^:private mlkem-params MLKEMParameters/ml_kem_768)
(def ^:private mldsa-params MLDSAParameters/ml_dsa_65)

(defn- assert-suite [suite]
  (when (not= suite PQ-SUITE)
    (throw (ex-info (str "[kotoba.lang.pqh/pq] unsupported suite: " suite) {:suite suite}))))

;; ── X25519 + ML-KEM-768 hybrid KEM ───────────────────────────────────────

(defn generate-hybrid-kem-key-pair
  "Fresh hybrid (X25519 + ML-KEM-768) KEM key pair:
   {:public-bundle {:suite :x25519-public-key :mlkem-public-key}
    :secret-bundle {:suite :x25519-secret-key :mlkem-secret-key}}"
  []
  (let [x-priv (X25519PrivateKeyParameters. secure-random)
        x-secret (.getEncoded x-priv)
        x-public (.getEncoded (.generatePublicKey x-priv))
        kpg (doto (MLKEMKeyPairGenerator.)
              (.init (MLKEMKeyGenerationParameters. secure-random mlkem-params)))
        kem-kp (.generateKeyPair kpg)
        kem-pub (.getEncoded ^MLKEMPublicKeyParameters (.getPublic kem-kp))
        kem-sec (.getEncoded ^MLKEMPrivateKeyParameters (.getPrivate kem-kp))]
    {:public-bundle {:suite PQ-SUITE :x25519-public-key x-public :mlkem-public-key kem-pub}
     :secret-bundle {:suite PQ-SUITE :x25519-secret-key x-secret :mlkem-secret-key kem-sec}}))

(defn- combine-shared-secrets
  "KEM combiner: HKDF-SHA256 over the concatenated classical + PQ shared
   secrets, with the full handshake transcript hash bound into `info`
   (X-Wing pattern)."
  ^bytes [{:keys [ss-classical ss-pq transcript info]}]
  (let [transcript-hash (u/sha256 (apply u/concat-bytes transcript))
        info-bytes (u/concat-bytes transcript-hash (or info (byte-array 0)))
        ikm (u/concat-bytes ss-classical ss-pq)
        gen (doto (HKDFBytesGenerator. (SHA256Digest.))
              (.init (HKDFParameters. ikm KEM-COMBINER-SALT info-bytes)))
        out (byte-array HYBRID-SHARED-SECRET-BYTES)]
    (.generateBytes gen out 0 HYBRID-SHARED-SECRET-BYTES)
    out))

(defn hybrid-encapsulate
  "Initiator side: encapsulate to a recipient's published bundle.
   Returns {:shared-secret bytes :handshake {:suite :x25519-ephemeral :mlkem-ciphertext}}."
  ([recipient] (hybrid-encapsulate recipient nil))
  ([recipient info]
   (assert-suite (:suite recipient))
   (let [eph-priv (X25519PrivateKeyParameters. secure-random)
         eph-public (.getEncoded (.generatePublicKey eph-priv))
         recipient-x-pub (X25519PublicKeyParameters. ^bytes (:x25519-public-key recipient))
         ss-classical (byte-array 32)
         _ (.generateSecret eph-priv recipient-x-pub ss-classical 0)
         recipient-mlkem-pub (MLKEMPublicKeyParameters. mlkem-params ^bytes (:mlkem-public-key recipient))
         gen (MLKEMGenerator. secure-random)
         encap (.generateEncapsulated gen recipient-mlkem-pub)
         cipher-text (.getEncapsulation encap)
         ss-pq (.getSecret encap)
         shared-secret (combine-shared-secrets
                         {:ss-classical ss-classical :ss-pq ss-pq
                          :transcript [eph-public cipher-text
                                       (:x25519-public-key recipient) (:mlkem-public-key recipient)]
                          :info info})]
     {:shared-secret shared-secret
      :handshake {:suite PQ-SUITE :x25519-ephemeral eph-public :mlkem-ciphertext cipher-text}})))

(defn hybrid-decapsulate
  "Responder side: derive the same shared secret from a received handshake.
   ML-KEM implicit rejection means a tampered ciphertext yields a *different*
   secret rather than an error; downstream AEAD authentication catches it."
  ([handshake secret recipient-public] (hybrid-decapsulate handshake secret recipient-public nil))
  ([handshake secret recipient-public info]
   (assert-suite (:suite handshake))
   (assert-suite (:suite secret))
   (let [priv (X25519PrivateKeyParameters. ^bytes (:x25519-secret-key secret))
         eph-pub (X25519PublicKeyParameters. ^bytes (:x25519-ephemeral handshake))
         ss-classical (byte-array 32)
         _ (.generateSecret priv eph-pub ss-classical 0)
         mlkem-priv (MLKEMPrivateKeyParameters. mlkem-params ^bytes (:mlkem-secret-key secret))
         extractor (MLKEMExtractor. mlkem-priv)
         ss-pq (.extractSecret extractor ^bytes (:mlkem-ciphertext handshake))]
     (combine-shared-secrets
       {:ss-classical ss-classical :ss-pq ss-pq
        :transcript [(:x25519-ephemeral handshake) (:mlkem-ciphertext handshake)
                     (:x25519-public-key recipient-public) (:mlkem-public-key recipient-public)]
        :info info}))))

;; ── ML-DSA-65 (FIPS 204) signature component ─────────────────────────────
;;
;; IMPORTANT DIVERGENCE FROM THE TS API (documented, deliberate -- see
;; README "Clojure/CLJC port" section for the full writeup):
;;
;; pq.ts's generateMlDsaKeyPair returns {publicKey, secretKey} where
;; secretKey is @noble/post-quantum's FIPS 204 *expanded* encoding (4032
;; bytes for ML-DSA-65). This port's generate-ml-dsa-key-pair instead
;; returns :secret-key as the 32-byte FIPS 204 *seed* -- verified to derive
;; a BYTE-IDENTICAL public key AND expanded-secret-key encoding to noble's
;; keygen(seed) for the same seed, and it is the only representation Bouncy
;; Castle 1.79's public API reliably reconstructs a signing-capable private
;; key from: independently re-verified in this port's test suite that even
;; BC's OWN freshly-generated expanded secret key, round-tripped through
;; `getEncoded()` and back through `(MLDSAPrivateKeyParameters. params
;; bytes)`, produces a signer that fails to verify -- i.e. that single-byte-
;; array constructor is not a general expanded-key decoder. The seed
;; representation is also FIPS 204's own NIST-recommended canonical storage
;; form. Consequence: a secretKey generated by this namespace is 32 bytes,
;; not 4032, and is NOT wire-compatible with a TS-side secretKey byte layout
;; -- but publicKey and every signature ARE fully cross-verified with noble.
;; This namespace's own generate+sign pair is internally consistent either
;; way, and secret keys never cross the wire in pq.ts's actual protocol.

(defn generate-ml-dsa-key-pair
  "Generate an ML-DSA-65 key pair. A 32-byte seed may be supplied for
   deterministic derivation; omit it for a random pair (a random 32-byte
   seed is generated either way -- see the namespace docstring for why
   :secret-key is that seed, not noble's 4032-byte expanded encoding)."
  ([] (generate-ml-dsa-key-pair nil))
  ([seed]
   (let [s (or seed (u/random-bytes 32))]
     (when (not= 32 (alength ^bytes s))
       (throw (ex-info "[kotoba.lang.pqh/pq] ML-DSA seed must be 32 bytes" {})))
     (let [priv (MLDSAPrivateKeyParameters. mldsa-params ^bytes s)]
       {:public-key (.getEncoded (.getPublicKeyParameters priv))
        :secret-key s}))))

(defn ml-dsa-sign
  "Sign a message with ML-DSA-65. secret-key is the 32-byte seed returned by
   generate-ml-dsa-key-pair (see namespace docstring)."
  ^bytes [^bytes secret-key ^bytes message]
  (let [priv (MLDSAPrivateKeyParameters. mldsa-params secret-key)
        signer (doto (MLDSASigner.) (.init true priv))]
    (.update signer message 0 (alength message))
    (.generateSignature signer)))

(defn ml-dsa-verify
  "Verify an ML-DSA-65 signature. public-key is the standard FIPS 204
   1952-byte encoding (fully cross-compatible with @noble/post-quantum).
   Returns false (never throws) on mismatch."
  [^bytes public-key ^bytes message ^bytes signature]
  (try
    (let [pub (MLDSAPublicKeyParameters. mldsa-params public-key)
          verifier (doto (MLDSASigner.) (.init false pub))]
      (.update verifier message 0 (alength message))
      (boolean (.verifySignature verifier signature)))
    (catch Exception _ false)))
